[{"id":1,"jpName":"113転び114起き","koName":"113전 114기","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":2,"jpName":"LookatCurren","koName":"LookatCurren","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":3,"jpName":"win Q.E.D.","koName":"win Q.E.D.","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":4,"jpName":"Adventure of 564","koName":"Adventure of 564","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":5,"jpName":"Best day ever","koName":"Best day ever","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":6,"jpName":"Do Ya Breakin!","koName":"Do Ya Breakin!","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":7,"jpName":"Drain for rose","koName":"Drain for rose","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":8,"jpName":"Fairy tale","koName":"Fairy tale","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":9,"jpName":"G00 1st.F∞;","koName":"G00 1st.F∞;","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":10,"jpName":"GET DOWN","koName":"GET DOWN","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":11,"jpName":"Go☆Go☆for it!","koName":"Go☆Go☆for it!","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":12,"jpName":"Guten Appetit♪","koName":"Guten Appetit♪","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":13,"jpName":"I Never Goof Up!","koName":"I Never Goof Up!","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":14,"jpName":"I'M☆FULL☆SPEED!!","koName":"I'M☆FULL☆SPEED!!","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":15,"jpName":"Joyful Voyage!","koName":"Joyful Voyage!","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":16,"jpName":"KEEP IT REAL.","koName":"KEEP IT REAL.","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":17,"jpName":"Nemesis","koName":"Nemesis","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":18,"jpName":"One True Color","koName":"One True Color","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":19,"jpName":"Presents from X","koName":"Presents from X","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":20,"jpName":"Pride of KING","koName":"Pride of KING","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":21,"jpName":"Ravissant","koName":"Ravissant","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":22,"jpName":"Schwarzes Schwert","koName":"Schwarzes Schwert","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":23,"jpName":"Shadow Break","koName":"Shadow Break","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":24,"jpName":"trigger:BEAT","koName":"trigger:BEAT","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":25,"jpName":"U=ma2","koName":"U=ma2","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":26,"jpName":"YEAH☆VIVID TIME!","koName":"YEAH☆VIVID TIME!","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":27,"jpName":"憧れは桜を越える！","koName":"동경은 벚꽃을 넘는다!","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":28,"jpName":"アナタヲ・オイカケテ","koName":"당신을 뒤쫓아서","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":29,"jpName":"アングリング×スキーミング","koName":"앵글링×스키밍","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":30,"jpName":"いただき☆ストレリチア！","koName":"받아라☆스트렐리치아","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":31,"jpName":"一期の夢、刹那の飛翔","koName":"일생의 꿈, 찰나의 비상","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":32,"jpName":"威風堂々、夢錦！","koName":"위풍당당, 유메니시키!","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":33,"jpName":"ヴィクトリーショット！","koName":"빅토리 샷!","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":34,"jpName":"ヴィットーリアに捧ぐ舞踏","koName":"빅토리아에게 바치는 무도","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":35,"jpName":"麗しき花信風","koName":"아름다운 화신풍","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":36,"jpName":"恵福バルカローレ","koName":"복을 베푸는 바르카롤","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":37,"jpName":"オペレーション・Cacao","koName":"오퍼레이션 Cacao","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":38,"jpName":"快走かな、快走かな！","koName":"쾌주로다, 쾌주로다!","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":39,"jpName":"晦冥を照らせ永遠の耀き","koName":"어둠을 비추는 영원한 반짝임","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":40,"jpName":"翳り退く、さざめきの矢","koName":"어스름은 물렀거라, 떠들썩함의 화살","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":41,"jpName":"勝ち鬨ワッショイ！","koName":"승리의 함성 어기여차!","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":42,"jpName":"カッティング×DRIVE！","koName":"커팅×DRIVE!","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":43,"jpName":"彼方、その先へ…","koName":"저편, 그 너머로…!","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":44,"jpName":"貴顕の使命を果たすべく","koName":"존귀한 사명을 완수하기 위하여","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":45,"jpName":"きっとその先へ…！","koName":"반드시 그 너머로...!","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":46,"jpName":"来ます来てます来させます！","koName":"옵니다 오고 있습니다 오게 할 겁니다!","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":47,"jpName":"究極テイオーステップ","koName":"궁극 테이오 스텝","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":48,"jpName":"キラキラ☆STARDOM","koName":"반짝반짝☆STARDOM","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":49,"jpName":"煌星のヴォードヴィル","koName":"황성의 보드빌","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":50,"jpName":"きらめくは海、まばゆきは君","koName":"반짝이는 건 바다, 눈부신 것은 너","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":51,"jpName":"グッときて♪Chu","koName":"뭉클하게♪Chu","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":52,"jpName":"ぐるぐるマミートリック♡","koName":"빙글빙글 머미 트릭♡","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":53,"jpName":"薫風、永遠なる瞬間を","koName":"훈풍, 영원한 순간을","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":54,"jpName":"ゲインヒール・スペリアー","koName":"게인힐·슈피리어","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":55,"jpName":"紅焔ギア/LP1211-M","koName":"홍염 기어 / LP1211-M","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":56,"jpName":"禾スナハチ登ル","koName":"벼가 곧 무르익는다","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":57,"jpName":"コンドル猛撃波","koName":"콘도르 맹격파","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":58,"jpName":"最強の名を懸けて","koName":"최강의 이름을 걸고","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":59,"jpName":"シューティングスター","koName":"슈팅스타","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":60,"jpName":"勝利の鼓動","koName":"승리의 고동","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":61,"jpName":"勝利のチケットを、君にッ！","koName":"승리의 티켓을 너에게!","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":62,"jpName":"白い稲妻、見せたるで！","koName":"하얀 번개, 보여 주꾸마!","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":63,"jpName":"精神一到何事か成らざらん","koName":"정신일도 하사불성","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":64,"jpName":"聖夜のミラクルラン！","koName":"크리스마스 이브의 미라클 런!","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":65,"jpName":"絶対は、ボクだ","koName":"반드시 이기는건 나야","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":66,"jpName":"先頭の景色は譲らない…！","koName":"선두의 경치는 양보할수없어...!","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":67,"jpName":"タイマン！デッドヒート！","koName":"맞짱! 데드히트!","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":68,"jpName":"チャージ完了！全速前進！","koName":"차지 완료! 전속 전진!","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":69,"jpName":"つぼみ、ほころぶ時","koName":"꽃봉오리, 피어날 때","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":70,"jpName":"ディオスクロイの流星","koName":"디오스쿠로이의 유성","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":71,"jpName":"尊み☆ﾗｽﾄｽﾊﾟ―(ﾟ∀ﾟ)―ﾄ!","koName":"존귀☆라스트 스퍼—(ﾟ∀ﾟ)—트!","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":72,"jpName":"ときめきが呼ぶほうへ","koName":"설렘이 부르는 방향으로","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":73,"jpName":"轟！トレセン応援団！！","koName":"울어라! 트레센 응원단!!","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":74,"jpName":"どんっ、パッ、むんっ","koName":"땅,팟,뭉!","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":75,"jpName":"汝、皇帝の神威を見よ","koName":"그대, 황제의 신위를 보라","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":76,"jpName":"姫たるもの、勝利をこの手に","koName":"공주라면, 우승을 이 손에","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":77,"jpName":"ピュリティオブハート","koName":"퓨리티 오브 하트","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":78,"jpName":"ひらめき☆ランディング","koName":"번뜩임☆랜딩","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":79,"jpName":"不沈艦、抜錨ォッ！","koName":"불침함, 출항!!","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":80,"jpName":"ぶっちぎりロード","koName":"따돌리기 로드","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":81,"jpName":"フラワリー☆マニューバ","koName":"플라워리☆메뉴버","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":82,"jpName":"プランチャ☆ガナドール","koName":"플란챠☆카나도르","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":83,"jpName":"ブリリアント・レッドエース","koName":"브릴리언트 레드 에이스","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":84,"jpName":"ブルーローズチェイサー","koName":"블루 로즈 체이서","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":85,"jpName":"ブレイズ・オブ・プライド","koName":"블레이즈 오브 프라이드","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":86,"jpName":"優等生×バクシン＝大勝利ッ","koName":"우등생x돌진=대승리!","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":87,"jpName":"烈火繚乱、無敵之舞","koName":"열화요란, 무적의 춤","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":88,"jpName":"レッツ・アナボリック！","koName":"레츠 아나볼릭","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":89,"jpName":"ワクワククライマックス","koName":"두근두근 클라이맥스","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":90,"jpName":"わやかわ♪マリンダイヴ","koName":"정말로 귀엽네♪머린 다이브","koCat1":"상속된 고유 스킬","jpCat1":"継承した固有スキル","koCat2":"공통","jpCat2":"共通","point":180},
{"id":91,"jpName":"一番星","koName":"샛별","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"공통","jpCat2":"共通","point":633},
{"id":92,"jpName":"ハヤテ一文字","koName":"한줄기 질풍","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"공통","jpCat2":"共通","point":508},
{"id":93,"jpName":"一陣の風","koName":"일진광풍","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"공통","jpCat2":"共通","point":508},
{"id":94,"jpName":"好転一息","koName":"호전일식","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"공통","jpCat2":"共通","point":508},
{"id":95,"jpName":"円弧のマエストロ","koName":"원호의 마에스트로","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"공통","jpCat2":"共通","point":508},
{"id":96,"jpName":"弧線のプロフェッサー","koName":"호선의 프로페서","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"공통","jpCat2":"共通","point":508},
{"id":97,"jpName":"アガッてきた！","koName":"텐션 오르는데!","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"공통","jpCat2":"共通","point":508},
{"id":98,"jpName":"コンセントレーション","koName":"컨센트레이션","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"공통","jpCat2":"共通","point":394},
{"id":99,"jpName":"良バ場の鬼","koName":"양호한 경기장의 귀신","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"공통","jpCat2":"共通","point":461},
{"id":100,"jpName":"右回りの鬼","koName":"시계(우)방향의 요괴","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"공통","jpCat2":"共通","point":461},
{"id":101,"jpName":"全身全霊","koName":"전심전력","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"공통","jpCat2":"共通","point":508},
{"id":102,"jpName":"博打うち","koName":"도박사","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"공통","jpCat2":"共通","point":334},
{"id":103,"jpName":"アオハル燃焼・速","koName":"아오하루 연소・속도","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"공통","jpCat2":"共通","point":633},
{"id":104,"jpName":"アオハル燃焼・体","koName":"아오하루 연소・체력","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"공통","jpCat2":"共通","point":633},
{"id":105,"jpName":"アオハル燃焼・力","koName":"아오하루 연소・힘","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"공통","jpCat2":"共通","point":633},
{"id":106,"jpName":"アオハル燃焼・根","koName":"아오하루 연소・근성","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"공통","jpCat2":"共通","point":633},
{"id":107,"jpName":"アオハル燃焼・賢","koName":"아오하루 연소・지능","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"공통","jpCat2":"共通","point":633},
{"id":108,"jpName":"曲線のソムリエ","koName":"곡선의 소믈리에","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"공통","jpCat2":"共通","point":508},
{"id":109,"jpName":"鋼の意志","koName":"강철 같은 의지","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"공통","jpCat2":"共通","point":508},
{"id":110,"jpName":"スーパーラッキーセブン","koName":"슈퍼 럭키 세븐","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"공통","jpCat2":"共通","point":334},
{"id":111,"jpName":"どこ吹く風","koName":"마이동풍","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"공통","jpCat2":"共通","point":508},
{"id":112,"jpName":"不屈の心","koName":"꺾이지 않는 마음","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"공통","jpCat2":"共通","point":508},
{"id":113,"jpName":"注目の踊り子","koName":"주목 받는 댄서","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"공통","jpCat2":"共通","point":334},
{"id":114,"jpName":"レーンの魔術師","koName":"라인의 마술사","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"공통","jpCat2":"共通","point":334},
{"id":115,"jpName":"ノンストップガール","koName":"논스톱 걸","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"공통","jpCat2":"共通","point":394},
{"id":116,"jpName":"ウママニア","koName":"우마무스메 마니아","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"공통","jpCat2":"共通","point":508},
{"id":117,"jpName":"見惚れるトリック","koName":"넋이 나가는 트릭","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"공통","jpCat2":"共通","point":508},
{"id":118,"jpName":"春一番","koName":"첫 봄바람","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"공통","jpCat2":"共通","point":461},
{"id":119,"jpName":"初嵐","koName":"첫 폭풍","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"공통","jpCat2":"共通","point":461},
{"id":120,"jpName":"淀の申し子","koName":"요도가 점지한 아이","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"공통","jpCat2":"共通","point":461},
{"id":121,"jpName":"尻尾の滝登り","koName":"꼬리의 폭포오르기","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"공통","jpCat2":"共通","point":508},
{"id":122,"jpName":"お先に失礼っ！","koName":"먼저 갑니다!","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"공통","jpCat2":"共通","point":508},
{"id":123,"jpName":"豪脚","koName":"강인한 다리","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"마일","jpCat2":"マイル","point":508},
{"id":124,"jpName":"慧眼","koName":"혜안","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"마일","jpCat2":"マイル","point":508},
{"id":125,"jpName":"ギアチェンジ","koName":"기어체인지","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"마일","jpCat2":"マイル","point":508},
{"id":126,"jpName":"アクセル全開！","koName":"액셀 전개!","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"마일","jpCat2":"マイル","point":508},
{"id":127,"jpName":"マイルの支配者","koName":"마일의 지배자","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"마일","jpCat2":"マイル","point":508},
{"id":128,"jpName":"姉御肌","koName":"여장부","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"마일","jpCat2":"マイル","point":334},
{"id":129,"jpName":"布陣","koName":"포진","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"마일","jpCat2":"マイル","point":508},
{"id":130,"jpName":"破竹の勢い","koName":"파죽지세","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"마일","jpCat2":"マイル","point":508},
{"id":131,"jpName":"スプリントターボ","koName":"스프린트 터보","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"단거리","jpCat2":"短距離","point":508},
{"id":132,"jpName":"悩殺術","koName":"뇌쇄술","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"단거리","jpCat2":"短距離","point":508},
{"id":133,"jpName":"意気衝天","koName":"의기충천","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"단거리","jpCat2":"短距離","point":508},
{"id":134,"jpName":"プランX","koName":"플랜 X","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"단거리","jpCat2":"短距離","point":508},
{"id":135,"jpName":"圧倒的リード","koName":"압도적 리드","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"단거리","jpCat2":"短距離","point":508},
{"id":136,"jpName":"電撃の煌めき","koName":"번갯불의 번뜩임","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"단거리","jpCat2":"短距離","point":508},
{"id":137,"jpName":"準備万全！","koName":"준비만전!","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"단거리","jpCat2":"短距離","point":394},
{"id":138,"jpName":"光芒一閃","koName":"광망일섬","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"중거리","jpCat2":"中距離","point":508},
{"id":139,"jpName":"キラーチューン","koName":"킬러 튠","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"중거리","jpCat2":"中距離","point":508},
{"id":140,"jpName":"ライトニングステップ","koName":"라이트닝 스텝","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"중거리","jpCat2":"中距離","point":394},
{"id":141,"jpName":"神業ステップ","koName":"신의 스텝","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"중거리","jpCat2":"中距離","point":508},
{"id":142,"jpName":"勝利への執念","koName":"승리를 향한 집념","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"중거리","jpCat2":"中距離","point":508},
{"id":143,"jpName":"独占力","koName":"독점력","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"중거리","jpCat2":"中距離","point":508},
{"id":144,"jpName":"魅惑のささやき","koName":"매혹의 속삭임","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"중거리","jpCat2":"中距離","point":508},
{"id":145,"jpName":"千里眼","koName":"천리안","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"중거리","jpCat2":"中距離","point":334},
{"id":146,"jpName":"切り開く者","koName":"개척자","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"중거리","jpCat2":"中距離","point":508},
{"id":147,"jpName":"決死の覚悟","koName":"결사의 각오","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"중거리","jpCat2":"中距離","point":508},
{"id":148,"jpName":"気炎万丈","koName":"기염만장","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"중거리","jpCat2":"中距離","point":508},
{"id":149,"jpName":"起死回生","koName":"기사회생","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"중거리","jpCat2":"中距離","point":508},
{"id":150,"jpName":"荒ぶる旋風","koName":"사나운 회오리바람","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"중거리","jpCat2":"中距離","point":508},
{"id":151,"jpName":"高揚感","koName":"고양감","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"중거리","jpCat2":"中距離","point":508},
{"id":152,"jpName":"光芒円刃","koName":"광망원인","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"중거리","jpCat2":"中距離","point":508},
{"id":153,"jpName":"日本一のウマ娘","koName":"일본 제일의 우마무스메","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"장거리","jpCat2":"長距離","point":508},
{"id":154,"jpName":"泰然自若","koName":"태연작약","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"장거리","jpCat2":"長距離","point":508},
{"id":155,"jpName":"クールダウン","koName":"쿨다운","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"장거리","jpCat2":"長距離","point":508},
{"id":156,"jpName":"火事場のバ鹿力","koName":"위기 앞의 저력","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"장거리","jpCat2":"長距離","point":508},
{"id":157,"jpName":"先陣の心得","koName":"선봉의 마음가짐","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"장거리","jpCat2":"長距離","point":508},
{"id":158,"jpName":"奇術師","koName":"요술사","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"장거리","jpCat2":"長距離","point":334},
{"id":159,"jpName":"内的体験","koName":"내적 체험","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"장거리","jpCat2":"長距離","point":508},
{"id":160,"jpName":"怒涛の追い上げ","koName":"노도의 추격","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"장거리","jpCat2":"長距離","point":508},
{"id":161,"jpName":"スタミナグリード","koName":"스태미나 그리드","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"장거리","jpCat2":"長距離","point":461},
{"id":162,"jpName":"VIP顔パス","koName":"VIP 프리패스","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"장거리","jpCat2":"長距離","point":508},
{"id":163,"jpName":"真打","koName":"노력의 결정체","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"장거리","jpCat2":"長距離","point":508},
{"id":164,"jpName":"烈風一閃","koName":"열풍일섬","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"장거리","jpCat2":"長距離","point":508},
{"id":165,"jpName":"一意専心","koName":"일의전심","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"장거리","jpCat2":"長距離","point":508},
{"id":166,"jpName":"先手必勝","koName":"선수필승","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"도주","jpCat2":"逃げ","point":334},
{"id":167,"jpName":"シックスセンス","koName":"식스센스","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"도주","jpCat2":"逃げ","point":334},
{"id":168,"jpName":"脱出術","koName":"탈출술","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"도주","jpCat2":"逃げ","point":508},
{"id":169,"jpName":"逃亡者","koName":"도망자","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"도주","jpCat2":"逃げ","point":508},
{"id":170,"jpName":"じゃじゃウマ娘","koName":"말괄량이 우마무스메","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"도주","jpCat2":"逃げ","point":508},
{"id":171,"jpName":"トップランナー","koName":"톱 러너","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"도주","jpCat2":"逃げ","point":508},
{"id":172,"jpName":"大逃げ","koName":"대도주","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"도주","jpCat2":"逃げ","point":370},
{"id":173,"jpName":"スピードスター","koName":"스피드스터","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"선행","jpCat2":"先行","point":508},
{"id":174,"jpName":"食いしん坊","koName":"먹보","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"선행","jpCat2":"先行","point":508},
{"id":175,"jpName":"技巧派","koName":"기교파","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"선행","jpCat2":"先行","point":334},
{"id":176,"jpName":"レースプランナー","koName":"레이스 플래너","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"선행","jpCat2":"先行","point":508},
{"id":177,"jpName":"余裕綽々","koName":"여유만만","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"선행","jpCat2":"先行","point":508},
{"id":178,"jpName":"決意の直滑降","koName":"결의의 직활강","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"선행","jpCat2":"先行","point":334},
{"id":179,"jpName":"幻惑のかく乱","koName":"현혹의 교란","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"선행","jpCat2":"先行","point":334},
{"id":180,"jpName":"くじけぬ精神","koName":"불굴의 정신","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"선행","jpCat2":"先行","point":334},
{"id":181,"jpName":"鍔迫り合い","koName":"치열한 접전","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"선행","jpCat2":"先行","point":508},
{"id":182,"jpName":"迅速果断","koName":"신속 과감","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"선입","jpCat2":"差し","point":508},
{"id":183,"jpName":"乗り換え上手","koName":"능숙한 환승","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"선입","jpCat2":"差し","point":508},
{"id":184,"jpName":"八方にらみ","koName":"사방팔방 째려보기","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"선입","jpCat2":"差し","point":508},
{"id":185,"jpName":"昇り龍","koName":"승천하는 용","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"선입","jpCat2":"差し","point":508},
{"id":186,"jpName":"努力家","koName":"노력가","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"선입","jpCat2":"差し","point":334},
{"id":187,"jpName":"大局観","koName":"대국관","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"선입","jpCat2":"差し","point":334},
{"id":188,"jpName":"リラックス","koName":"릴랙스","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"선입","jpCat2":"差し","point":508},
{"id":189,"jpName":"百万バリキ","koName":"백만마력","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"선입","jpCat2":"差し","point":334},
{"id":190,"jpName":"潜伏態勢","koName":"잠복 태세","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"선입","jpCat2":"差し","point":508},
{"id":191,"jpName":"大胆不敵","koName":"대담무쌍","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"선입","jpCat2":"差し","point":508},
{"id":192,"jpName":"勇往邁進","koName":"용왕매진","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"선입","jpCat2":"差し","point":508},
{"id":193,"jpName":"視界良好！異常なし！","koName":"시야 양호! 이상 없음!","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"추입","jpCat2":"追込","point":334},
{"id":194,"jpName":"眠れる獅子","koName":"잠자는 사자","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"추입","jpCat2":"追込","point":508},
{"id":195,"jpName":"下校後のスペシャリスト","koName":"하교 후의 스페셜리스트","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"추입","jpCat2":"追込","point":508},
{"id":196,"jpName":"迫る影","koName":"육박하는 그림자","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"추입","jpCat2":"追込","point":508},
{"id":197,"jpName":"疾風怒濤","koName":"질풍노도","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"추입","jpCat2":"追込","point":508},
{"id":198,"jpName":"天命士","koName":"천명사","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"추입","jpCat2":"追込","point":334},
{"id":199,"jpName":"強攻策","koName":"강공책","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"추입","jpCat2":"追込","point":508},
{"id":200,"jpName":"冷静沈着","koName":"냉정침착","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"추입","jpCat2":"追込","point":508},
{"id":201,"jpName":"月影一閃","koName":"월영일섬","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"추입","jpCat2":"追込","point":508},
{"id":202,"jpName":"熱いまなざし","koName":"뜨거운 시선","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"추입","jpCat2":"追込","point":508},
{"id":203,"jpName":"チャート急上昇！","koName":"차트 급상승!","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"더트","jpCat2":"ダート","point":508},
{"id":204,"jpName":"狙うは最前列！","koName":"목표는 맨 앞줄!","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"더트","jpCat2":"ダート","point":394},
{"id":205,"jpName":"砂の玄人","koName":"모래의 현자","koCat1":"금 스킬","jpCat1":"金スキル","koCat2":"더트","jpCat2":"ダート","point":508},
{"id":206,"jpName":"綺羅星","koName":"기라성","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"공통","jpCat2":"共通","point":263},
{"id":207,"jpName":"直線巧者","koName":"직선 달인","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"공통","jpCat2":"共通","point":217},
{"id":208,"jpName":"直線加速","koName":"직선 가속","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"공통","jpCat2":"共通","point":217},
{"id":209,"jpName":"末脚","koName":"뒷심","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"공통","jpCat2":"共通","point":217},
{"id":210,"jpName":"垂れウマ回避","koName":"뒤쳐지기 방지","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"공통","jpCat2":"共通","point":174},
{"id":211,"jpName":"コーナー巧者○","koName":"코너 달인○","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"공통","jpCat2":"共通","point":217},
{"id":212,"jpName":"コーナー加速○","koName":"코너 가속○","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"공통","jpCat2":"共通","point":217},
{"id":213,"jpName":"アオハル点火・速","koName":"아오하루 점화・속도","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"공통","jpCat2":"共通","point":263},
{"id":214,"jpName":"アオハル点火・力","koName":"아오하루 점화・힘","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"공통","jpCat2":"共通","point":263},
{"id":215,"jpName":"アオハル点火・根","koName":"아오하루 점화・근성","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"공통","jpCat2":"共通","point":263},
{"id":216,"jpName":"アオハル点火・賢","koName":"아오하루 점화・지능","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"공통","jpCat2":"共通","point":263},
{"id":217,"jpName":"臨機応変","koName":"임기응변","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"공통","jpCat2":"共通","point":129},
{"id":218,"jpName":"集中力","koName":"집중력","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"공통","jpCat2":"共通","point":129},
{"id":219,"jpName":"地固め","koName":"터다지기","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"공통","jpCat2":"共通","point":217},
{"id":220,"jpName":"尻尾上がり","koName":"꼬리 올리기","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"공통","jpCat2":"共通","point":217},
{"id":221,"jpName":"あやしげな作戦","koName":"수상한 작전","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"공통","jpCat2":"共通","point":129},
{"id":222,"jpName":"ペースアップ","koName":"페이스 업","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"공통","jpCat2":"共通","point":217},
{"id":223,"jpName":"ポジションセンス","koName":"포지션 센스","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"공통","jpCat2":"共通","point":129},
{"id":224,"jpName":"登山家","koName":"등산가","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"공통","jpCat2":"共通","point":217},
{"id":225,"jpName":"ウマ好み","koName":"우마무스메 애호가","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"공통","jpCat2":"共通","point":217},
{"id":226,"jpName":"スリップストリーム","koName":"슬립 스트림","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"공통","jpCat2":"共通","point":217},
{"id":227,"jpName":"遊びはおしまいっ！","koName":"장난은 끝이야!","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"공통","jpCat2":"共通","point":217},
{"id":228,"jpName":"下り坂巧者","koName":"내리막 숙련자","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"공통","jpCat2":"共通","point":217},
{"id":229,"jpName":"短距離直線○","koName":"후쿠시마 경기장○","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"단거리","jpCat2":"短距離","point":217},
{"id":230,"jpName":"短距離直線◎","koName":"후쿠시마 경기장◎","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"단거리","jpCat2":"短距離","point":262},
{"id":231,"jpName":"短距離コーナー○","koName":"단거리코너○","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"단거리","jpCat2":"短距離","point":217},
{"id":232,"jpName":"短距離コーナー◎","koName":"단거리코너◎","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"단거리","jpCat2":"短距離","point":262},
{"id":233,"jpName":"軽い足取り","koName":"경쾌한 발걸음","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"단거리","jpCat2":"短距離","point":217},
{"id":234,"jpName":"マイル直線○","koName":"마일 직선○","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"마일","jpCat2":"マイル","point":217},
{"id":235,"jpName":"マイル直線◎","koName":"마일 직선◎","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"마일","jpCat2":"マイル","point":262},
{"id":236,"jpName":"マイルコーナー○","koName":"마일 코너○","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"마일","jpCat2":"マイル","point":217},
{"id":237,"jpName":"マイルコーナー◎","koName":"마일 코너◎","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"마일","jpCat2":"マイル","point":262},
{"id":238,"jpName":"中距離直線○","koName":"중거리 직선○","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"중거리","jpCat2":"中距離","point":217},
{"id":239,"jpName":"中距離直線◎","koName":"중거리 직선◎","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"중거리","jpCat2":"中距離","point":262},
{"id":240,"jpName":"中距離コーナー○","koName":"중거리 코너○","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"중거리","jpCat2":"中距離","point":217},
{"id":241,"jpName":"中距離コーナー◎","koName":"중거리 코너◎","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"중거리","jpCat2":"中距離","point":262},
{"id":242,"jpName":"長距離直線○","koName":"장거리 직선○","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"장거리","jpCat2":"長距離","point":217},
{"id":243,"jpName":"長距離直線◎","koName":"장거리 직선◎","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"장거리","jpCat2":"長距離","point":262},
{"id":244,"jpName":"長距離コーナー○","koName":"장거리 코너○","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"장거리","jpCat2":"長距離","point":217},
{"id":245,"jpName":"長距離コーナー◎","koName":"장거리 코너◎","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"장거리","jpCat2":"長距離","point":262},
{"id":246,"jpName":"逃げ直線○","koName":"도주 직선○","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"도주","jpCat2":"逃げ","point":217},
{"id":247,"jpName":"逃げ直線◎","koName":"도주 직선◎","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"도주","jpCat2":"逃げ","point":262},
{"id":248,"jpName":"逃げコーナー○","koName":"도주코너○","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"도주","jpCat2":"逃げ","point":217},
{"id":249,"jpName":"逃げコーナー◎","koName":"도주코너◎","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"도주","jpCat2":"逃げ","point":262},
{"id":250,"jpName":"先行直線○","koName":"선행 직선○","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"선행","jpCat2":"先行","point":217},
{"id":251,"jpName":"先行直線◎","koName":"선행 직선◎","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"선행","jpCat2":"先行","point":262},
{"id":252,"jpName":"先行コーナー○","koName":"선행 코너○","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"선행","jpCat2":"先行","point":217},
{"id":253,"jpName":"先行コーナー◎","koName":"선행 코너◎","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"선행","jpCat2":"先行","point":262},
{"id":254,"jpName":"差し直線○","koName":"선입 직선○","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"선입","jpCat2":"差し","point":217},
{"id":255,"jpName":"差し直線◎","koName":"선입 직선◎","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"선입","jpCat2":"差し","point":262},
{"id":256,"jpName":"差しコーナー○","koName":"선입 코너○","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"선입","jpCat2":"差し","point":217},
{"id":257,"jpName":"差しコーナー◎","koName":"선입 코너◎","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"선입","jpCat2":"差し","point":262},
{"id":258,"jpName":"追込直線○","koName":"추입 직선○","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"추입","jpCat2":"追込","point":217},
{"id":259,"jpName":"追込直線◎","koName":"추입 직선◎","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"추입","jpCat2":"追込","point":262},
{"id":260,"jpName":"追込コーナー○","koName":"추입 코너○","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"추입","jpCat2":"追込","point":217},
{"id":261,"jpName":"追込コーナー◎","koName":"추입 코너◎","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"추입","jpCat2":"追込","point":262},
{"id":262,"jpName":"大きなリード","koName":"큰 리드","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"단거리","jpCat2":"短距離","point":262},
{"id":263,"jpName":"スプリントギア","koName":"스프린트 기어","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"단거리","jpCat2":"短距離","point":217},
{"id":264,"jpName":"詰め寄り","koName":"바짝 붙기","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"단거리","jpCat2":"短距離","point":217},
{"id":265,"jpName":"善後策","koName":"선후책","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"단거리","jpCat2":"短距離","point":217},
{"id":266,"jpName":"仕掛け準備","koName":"작전 준비","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"단거리","jpCat2":"短距離","point":174},
{"id":267,"jpName":"積極策","koName":"적극책","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"마일","jpCat2":"マイル","point":217},
{"id":268,"jpName":"上昇気流","koName":"상승 기류","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"마일","jpCat2":"マイル","point":217},
{"id":269,"jpName":"ギアシフト","koName":"기어 시프트","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"마일","jpCat2":"マイル","point":217},
{"id":270,"jpName":"アクセラレーション","koName":"엑셀러레이션","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"마일","jpCat2":"マイル","point":217},
{"id":271,"jpName":"負けん気","koName":"오기","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"마일","jpCat2":"マイル","point":217},
{"id":272,"jpName":"気合十分","koName":"기합충분","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"마일","jpCat2":"マイル","point":217},
{"id":273,"jpName":"テンポアップ","koName":"템포 업","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"중거리","jpCat2":"中距離","point":217},
{"id":274,"jpName":"食い下がり","koName":"물고 늘어지기","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"중거리","jpCat2":"中距離","point":217},
{"id":275,"jpName":"ホークアイ","koName":"호크아이","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"중거리","jpCat2":"中距離","point":129},
{"id":276,"jpName":"イナズマステップ","koName":"라이트닝 스텝","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"중거리","jpCat2":"中距離","point":174},
{"id":277,"jpName":"ありったけ","koName":"남김 없이","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"중거리","jpCat2":"中距離","point":217},
{"id":278,"jpName":"闘争心","koName":"투쟁심","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"중거리","jpCat2":"中距離","point":217},
{"id":279,"jpName":"ワンチャンス","koName":"원 찬스","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"중거리","jpCat2":"中距離","point":217},
{"id":280,"jpName":"前のめり","koName":"앞으로 기우뚱","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"중거리","jpCat2":"中距離","point":217},
{"id":281,"jpName":"気迫を込めて","koName":"기백을 담아서","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"중거리","jpCat2":"中距離","point":217},
{"id":282,"jpName":"リードキープ","koName":"리드 킵","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"장거리","jpCat2":"長距離","point":217},
{"id":283,"jpName":"追い上げ","koName":"추격","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"장거리","jpCat2":"長距離","point":217},
{"id":284,"jpName":"内弁慶","koName":"안쪽 코너 여포","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"장거리","jpCat2":"長距離","point":217},
{"id":285,"jpName":"影打","koName":"노력의 결과","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"장거리","jpCat2":"長距離","point":217},
{"id":286,"jpName":"先駆け","koName":"앞장서기","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"도주","jpCat2":"逃げ","point":217},
{"id":287,"jpName":"急ぎ足","koName":"빠른 걸음","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"도주","jpCat2":"逃げ","point":217},
{"id":288,"jpName":"押し切り準備","koName":"굳히기 준비","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"도주","jpCat2":"逃げ","point":217},
{"id":289,"jpName":"先頭プライド","koName":"선두 프라이드","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"도주","jpCat2":"逃げ","point":217},
{"id":290,"jpName":"二の矢","koName":"두 번째 화살","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"도주","jpCat2":"逃げ","point":217},
{"id":291,"jpName":"危険回避","koName":"위험 회피","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"도주","jpCat2":"逃げ","point":129},
{"id":292,"jpName":"抜け出し準備","koName":"빠져나갈 준비","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"선행","jpCat2":"先行","point":217},
{"id":293,"jpName":"巧みなステップ","koName":"교묘한 스탭","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"선행","jpCat2":"先行","point":217},
{"id":294,"jpName":"直滑降","koName":"직활강","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"선행","jpCat2":"先行","point":217},
{"id":295,"jpName":"真っ向勝負","koName":"정면 승부","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"선행","jpCat2":"先行","point":217},
{"id":296,"jpName":"まき直し","koName":"새 출발","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"선행","jpCat2":"先行","point":217},
{"id":297,"jpName":"がんばり屋","koName":"근면한 태도","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"선입","jpCat2":"差し","point":217},
{"id":298,"jpName":"十万バリキ","koName":"십만 마력","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"선입","jpCat2":"差し","point":217},
{"id":299,"jpName":"位置取り押し上げ","koName":"위치 선정 밀어붙이기","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"선입","jpCat2":"差し","point":217},
{"id":300,"jpName":"差し切り体勢","koName":"추월 확정 태세","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"선입","jpCat2":"差し","point":217},
{"id":301,"jpName":"外差し準備","koName":"외곽 추월 준비","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"선입","jpCat2":"差し","point":217},
{"id":302,"jpName":"読解力","koName":"독해력","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"선입","jpCat2":"差し","point":85},
{"id":303,"jpName":"恐れぬ心","koName":"두려워 하지 않는 마음","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"선입","jpCat2":"差し","point":217},
{"id":304,"jpName":"フルスロットル","koName":"풀 스로틀","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"선입","jpCat2":"差し","point":217},
{"id":305,"jpName":"お見通し","koName":"간파","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"추입","jpCat2":"追込","point":85},
{"id":306,"jpName":"策士","koName":"책사","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"추입","jpCat2":"追込","point":85},
{"id":307,"jpName":"仕掛け抜群","koName":"뛰어난 작전","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"추입","jpCat2":"追込","point":217},
{"id":308,"jpName":"直線一気","koName":"직선 주파","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"추입","jpCat2":"追込","point":217},
{"id":309,"jpName":"早仕掛け","koName":"이른 작전","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"추입","jpCat2":"追込","point":217},
{"id":310,"jpName":"レコメンド","koName":"리커맨드","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"더트","jpCat2":"ダート","point":217},
{"id":311,"jpName":"前列狙い","koName":"앞줄겨냥","koCat1":"주황 스킬","jpCat1":"オレンジスキル","koCat2":"더트","jpCat2":"ダート","point":174},
{"id":312,"jpName":"コーナー回復○","koName":"코너 회복◯","koCat1":"청 스킬","jpCat1":"青スキル","koCat2":"공통","jpCat2":"共通","point":217},
{"id":313,"jpName":"直線回復","koName":"직선 회복","koCat1":"청 스킬","jpCat1":"青スキル","koCat2":"공통","jpCat2":"共通","point":217},
{"id":314,"jpName":"アオハル点火・体","koName":"아오하루 점화・체력","koCat1":"청 스킬","jpCat1":"青スキル","koCat2":"공통","jpCat2":"共通","point":263},
{"id":315,"jpName":"ペースキープ","koName":"페이스 킵","koCat1":"청 스킬","jpCat1":"青スキル","koCat2":"공통","jpCat2":"共通","point":217},
{"id":316,"jpName":"ウマ込み冷静","koName":"마군 속 냉정","koCat1":"청 스킬","jpCat1":"青スキル","koCat2":"공통","jpCat2":"共通","point":217},
{"id":317,"jpName":"ふり絞り","koName":"쥐어짜기","koCat1":"청 스킬","jpCat1":"青スキル","koCat2":"공통","jpCat2":"共通","point":217},
{"id":318,"jpName":"隠れ蓑","koName":"방패막이","koCat1":"청 스킬","jpCat1":"青スキル","koCat2":"공통","jpCat2":"共通","point":217},
{"id":319,"jpName":"スリーセブン","koName":"쓰리 세븐","koCat1":"청 스킬","jpCat1":"青スキル","koCat2":"공통","jpCat2":"共通","point":217},
{"id":320,"jpName":"様子見","koName":"지켜보기","koCat1":"청 스킬","jpCat1":"青スキル","koCat2":"단거리","jpCat2":"短距離","point":217},
{"id":321,"jpName":"展開窺い","koName":"전개 살피기","koCat1":"청 스킬","jpCat1":"青スキル","koCat2":"마일","jpCat2":"マイル","point":217},
{"id":322,"jpName":"前途洋々","koName":"전도유망","koCat1":"청 스킬","jpCat1":"青スキル","koCat2":"중거리","jpCat2":"中距離","point":217},
{"id":323,"jpName":"軽やかステップ","koName":"경쾌한 스텝","koCat1":"청 스킬","jpCat1":"青スキル","koCat2":"중거리","jpCat2":"中距離","point":217},
{"id":324,"jpName":"マイペース","koName":"마이 페이스","koCat1":"청 스킬","jpCat1":"青スキル","koCat2":"장거리","jpCat2":"長距離","point":217},
{"id":325,"jpName":"深呼吸","koName":"심호흡","koCat1":"청 스킬","jpCat1":"青スキル","koCat2":"장거리","jpCat2":"長距離","point":217},
{"id":326,"jpName":"別腹タンク","koName":"외장탱크","koCat1":"청 스킬","jpCat1":"青スキル","koCat2":"장거리","jpCat2":"長距離","point":217},
{"id":327,"jpName":"パス上手","koName":"능숙한 패스","koCat1":"청 스킬","jpCat1":"青スキル","koCat2":"장거리","jpCat2":"長距離","point":217},
{"id":328,"jpName":"抜かりなし","koName":"빈틈 없음","koCat1":"청 스킬","jpCat1":"青スキル","koCat2":"장거리","jpCat2":"長距離","point":217},
{"id":329,"jpName":"勢い任せ","koName":"기세에 맡기기","koCat1":"청 스킬","jpCat1":"青スキル","koCat2":"도주","jpCat2":"逃げ","point":217},
{"id":330,"jpName":"スタミナキープ","koName":"스태미나 킵","koCat1":"청 스킬","jpCat1":"青スキル","koCat2":"선행","jpCat2":"先行","point":217},
{"id":331,"jpName":"好位追走","koName":"좋은 위치 뒤따르기","koCat1":"청 스킬","jpCat1":"青スキル","koCat2":"선행","jpCat2":"先行","point":217},
{"id":332,"jpName":"栄養補給","koName":"영양보급","koCat1":"청 스킬","jpCat1":"青スキル","koCat2":"선행","jpCat2":"先行","point":217},
{"id":333,"jpName":"小休憩","koName":"짧은 휴식","koCat1":"청 스킬","jpCat1":"青スキル","koCat2":"선입","jpCat2":"差し","point":217},
{"id":334,"jpName":"静かな呼吸","koName":"조용한 호흡","koCat1":"청 스킬","jpCat1":"青スキル","koCat2":"선입","jpCat2":"差し","point":217},
{"id":335,"jpName":"後方待機","koName":"후방 대기","koCat1":"청 스킬","jpCat1":"青スキル","koCat2":"추입","jpCat2":"追込","point":217},
{"id":336,"jpName":"冷静","koName":"냉정","koCat1":"청 스킬","jpCat1":"青スキル","koCat2":"추입","jpCat2":"追込","point":217},
{"id":337,"jpName":"下校の楽しみ","koName":"하굣길의 즐거움","koCat1":"청 스킬","jpCat1":"青スキル","koCat2":"추입","jpCat2":"追込","point":217},
{"id":338,"jpName":"砂塵慣れ","koName":"모래 먼지 익숙해지기","koCat1":"청 스킬","jpCat1":"青スキル","koCat2":"더트","jpCat2":"ダート","point":217},
{"id":339,"jpName":"根幹距離○","koName":"근간거리○","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"공통","jpCat2":"共通","point":129},
{"id":340,"jpName":"根幹距離◎","koName":"근간거리◎","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"공통","jpCat2":"共通","point":174},
{"id":341,"jpName":"非根幹距離○","koName":"비근간거리○","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"공통","jpCat2":"共通","point":129},
{"id":342,"jpName":"非根幹距離◎","koName":"비근간거리◎","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"공통","jpCat2":"共通","point":174},
{"id":343,"jpName":"右回り○","koName":"시계(우) 방향○","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"공통","jpCat2":"共通","point":129},
{"id":344,"jpName":"右回り◎","koName":"시계(우) 방향◎","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"공통","jpCat2":"共通","point":174},
{"id":345,"jpName":"左回り○","koName":"반시계(좌) 방향○","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"공통","jpCat2":"共通","point":129},
{"id":346,"jpName":"左回り◎","koName":"반시계(좌) 방향◎","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"공통","jpCat2":"共通","point":174},
{"id":347,"jpName":"良バ場○","koName":"양호한 경기장○","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"공통","jpCat2":"共通","point":129},
{"id":348,"jpName":"良バ場◎","koName":"양호한 경기장◎","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"공통","jpCat2":"共通","point":174},
{"id":349,"jpName":"道悪○","koName":"진창길○","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"공통","jpCat2":"共通","point":129},
{"id":350,"jpName":"道悪◎","koName":"진창길◎","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"공통","jpCat2":"共通","point":174},
{"id":351,"jpName":"逃げのコツ○","koName":"도주의 요령○","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"도주","jpCat2":"逃げ","point":174},
{"id":352,"jpName":"逃げのコツ◎","koName":"도주의 요령◎","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"도주","jpCat2":"逃げ","point":217},
{"id":353,"jpName":"先行のコツ○","koName":"선행의 요령○","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"선행","jpCat2":"先行","point":174},
{"id":354,"jpName":"先行のコツ◎","koName":"선행의 요령◎","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"선행","jpCat2":"先行","point":217},
{"id":355,"jpName":"差しのコツ○","koName":"선입의 요령○","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"선입","jpCat2":"差し","point":174},
{"id":356,"jpName":"差しのコツ◎","koName":"선입의 요령◎","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"선입","jpCat2":"差し","point":217},
{"id":357,"jpName":"追込のコツ○","koName":"추입의 요령○","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"추입","jpCat2":"追込","point":174},
{"id":358,"jpName":"追込のコツ◎","koName":"추입의 요령◎","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"추입","jpCat2":"追込","point":217},
{"id":359,"jpName":"シンパシー","koName":"심퍼시","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"공통","jpCat2":"共通","point":129},
{"id":360,"jpName":"一匹狼","koName":"고독한 늑대","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"공통","jpCat2":"共通","point":129},
{"id":361,"jpName":"ラッキーセブン","koName":"럭키 세븐","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"공통","jpCat2":"共通","point":174},
{"id":362,"jpName":"おひとり様○","koName":"단독○","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"공통","jpCat2":"共通","point":129},
{"id":363,"jpName":"おひとり様◎","koName":"단독◎","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"공통","jpCat2":"共通","point":174},
{"id":364,"jpName":"自制心","koName":"자제심","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"공통","jpCat2":"共通","point":217},
{"id":365,"jpName":"伏兵○","koName":"복병○","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"공통","jpCat2":"共通","point":129},
{"id":366,"jpName":"伏兵◎","koName":"복병◎","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"공통","jpCat2":"共通","point":174},
{"id":367,"jpName":"徹底マーク○","koName":"집중마크○","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"공통","jpCat2":"共通","point":129},
{"id":368,"jpName":"徹底マーク◎","koName":"집중마크◎","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"공통","jpCat2":"共通","point":174},
{"id":369,"jpName":"対抗意識○","koName":"대항의식○","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"공통","jpCat2":"共通","point":129},
{"id":370,"jpName":"対抗意識◎","koName":"대항의식◎","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"공통","jpCat2":"共通","point":174},
{"id":371,"jpName":"晴れの日○","koName":"맑은날○","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"공통","jpCat2":"共通","point":129},
{"id":372,"jpName":"晴れの日◎","koName":"맑은날◎","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"공통","jpCat2":"共通","point":174},
{"id":373,"jpName":"曇りの日○","koName":"흐린날○","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"공통","jpCat2":"共通","point":129},
{"id":374,"jpName":"曇りの日◎","koName":"흐린날◎","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"공통","jpCat2":"共通","point":174},
{"id":375,"jpName":"雨の日○","koName":"비오는 날○","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"공통","jpCat2":"共通","point":129},
{"id":376,"jpName":"雨の日◎","koName":"비오는 날◎","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"공통","jpCat2":"共通","point":174},
{"id":377,"jpName":"雪の日○","koName":"눈 오는 날○","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"공통","jpCat2":"共通","point":129},
{"id":378,"jpName":"雪の日◎","koName":"눈 오는 날◎","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"공통","jpCat2":"共通","point":174},
{"id":379,"jpName":"東京レース場○","koName":"도쿄 경기장○","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"공통","jpCat2":"共通","point":129},
{"id":380,"jpName":"東京レース場◎","koName":"도쿄 경기장◎","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"공통","jpCat2":"共通","point":174},
{"id":381,"jpName":"中山レース場○","koName":"나카야마 경기장○","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"공통","jpCat2":"共通","point":129},
{"id":382,"jpName":"中山レース場◎","koName":"나카야마 경기장◎","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"공통","jpCat2":"共通","point":174},
{"id":383,"jpName":"阪神レース場○","koName":"한신 경기장○","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"공통","jpCat2":"共通","point":129},
{"id":384,"jpName":"阪神レース場◎","koName":"한신 경기장◎","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"공통","jpCat2":"共通","point":174},
{"id":385,"jpName":"京都レース場○","koName":"교토 경기장○","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"공통","jpCat2":"共通","point":129},
{"id":386,"jpName":"京都レース場◎","koName":"교토 경기장◎","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"공통","jpCat2":"共通","point":174},
{"id":387,"jpName":"中京レース場○","koName":"나카교 경기장○","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"공통","jpCat2":"共通","point":129},
{"id":388,"jpName":"中京レース場◎","koName":"나카교 경기장◎","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"공통","jpCat2":"共通","point":174},
{"id":389,"jpName":"札幌レース場○","koName":"삿포로 경기장○","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"공통","jpCat2":"共通","point":129},
{"id":390,"jpName":"札幌レース場◎","koName":"삿포로 경기장◎","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"공통","jpCat2":"共通","point":174},
{"id":391,"jpName":"函館レース場○","koName":"하코다테 경기장○","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"공통","jpCat2":"共通","point":129},
{"id":392,"jpName":"函館レース場◎","koName":"하코다테 경기장◎","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"공통","jpCat2":"共通","point":174},
{"id":393,"jpName":"福島レース場○","koName":"후쿠시마 경기장○","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"공통","jpCat2":"共通","point":129},
{"id":394,"jpName":"福島レース場◎","koName":"후쿠시마 경기장◎","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"공통","jpCat2":"共通","point":174},
{"id":395,"jpName":"新潟レース場○","koName":"니가타 경기장○","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"공통","jpCat2":"共通","point":129},
{"id":396,"jpName":"新潟レース場◎","koName":"니가타 경기장◎","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"공통","jpCat2":"共通","point":174},
{"id":397,"jpName":"大井レース場○","koName":"오이 경기장○","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"공통","jpCat2":"共通","point":129},
{"id":398,"jpName":"大井レース場◎","koName":"오이 경기장◎","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"공통","jpCat2":"共通","point":174},
{"id":399,"jpName":"小倉レース場○","koName":"코쿠라 경기장○","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"공통","jpCat2":"共通","point":129},
{"id":400,"jpName":"小倉レース場◎","koName":"코쿠라 경기장◎","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"공통","jpCat2":"共通","point":174},
{"id":401,"jpName":"春ウマ娘○","koName":"봄 우마무스메○","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"공통","jpCat2":"共通","point":129},
{"id":402,"jpName":"春ウマ娘◎","koName":"봄 우마무스메◎","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"공통","jpCat2":"共通","point":174},
{"id":403,"jpName":"夏ウマ娘○","koName":"여름 우마무스메○","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"공통","jpCat2":"共通","point":129},
{"id":404,"jpName":"夏ウマ娘◎","koName":"여름 우마무스메◎","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"공통","jpCat2":"共通","point":174},
{"id":405,"jpName":"秋ウマ娘○","koName":"가을 우마무스메○","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"공통","jpCat2":"共通","point":129},
{"id":406,"jpName":"秋ウマ娘◎","koName":"가을 우마무스메◎","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"공통","jpCat2":"共通","point":174},
{"id":407,"jpName":"冬ウマ娘○","koName":"겨울 우마무스메○","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"공통","jpCat2":"共通","point":129},
{"id":408,"jpName":"冬ウマ娘◎","koName":"겨울 우마무스메◎","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"공통","jpCat2":"共通","point":174},
{"id":409,"jpName":"内枠得意○","koName":"안쪽 그룹 능숙◎","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"공통","jpCat2":"共通","point":129},
{"id":410,"jpName":"内枠得意◎","koName":"안쪽 그룹 능숙◎","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"공통","jpCat2":"共通","point":174},
{"id":411,"jpName":"外枠得意○","koName":"바깥쪽 그룹 능숙○","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"공통","jpCat2":"共通","point":129},
{"id":412,"jpName":"外枠得意◎","koName":"바깥쪽 그룹 능숙◎","koCat1":"연두 스킬","jpCat1":"緑スキル","koCat2":"공통","jpCat2":"共通","point":174},
{"id":413,"jpName":"逃げけん制","koName":"도주 견제","koCat1":"적 스킬","jpCat1":"赤スキル","koCat2":"공통","jpCat2":"共通","point":217},
{"id":414,"jpName":"逃げ焦り","koName":"도주 긴장","koCat1":"적 스킬","jpCat1":"赤スキル","koCat2":"공통","jpCat2":"共通","point":217},
{"id":415,"jpName":"逃げためらい","koName":"도주 주저","koCat1":"적 스킬","jpCat1":"赤スキル","koCat2":"공통","jpCat2":"共通","point":217},
{"id":416,"jpName":"先行けん制","koName":"선행 견제","koCat1":"적 스킬","jpCat1":"赤スキル","koCat2":"공통","jpCat2":"共通","point":217},
{"id":417,"jpName":"先行焦り","koName":"선행 긴장","koCat1":"적 스킬","jpCat1":"赤スキル","koCat2":"공통","jpCat2":"共通","point":217},
{"id":418,"jpName":"先行ためらい","koName":"선행 주저","koCat1":"적 스킬","jpCat1":"赤スキル","koCat2":"공통","jpCat2":"共通","point":217},
{"id":419,"jpName":"差しけん制","koName":"선입 견제","koCat1":"적 스킬","jpCat1":"赤スキル","koCat2":"공통","jpCat2":"共通","point":217},
{"id":420,"jpName":"差し焦り","koName":"선입 긴장","koCat1":"적 스킬","jpCat1":"赤スキル","koCat2":"공통","jpCat2":"共通","point":217},
{"id":421,"jpName":"差しためらい","koName":"선입 주저","koCat1":"적 스킬","jpCat1":"赤スキル","koCat2":"공통","jpCat2":"共通","point":217},
{"id":422,"jpName":"追込けん制","koName":"추입 견제","koCat1":"적 스킬","jpCat1":"赤スキル","koCat2":"공통","jpCat2":"共通","point":217},
{"id":423,"jpName":"追込焦り","koName":"추입 긴장","koCat1":"적 스킬","jpCat1":"赤スキル","koCat2":"공통","jpCat2":"共通","point":217},
{"id":424,"jpName":"追込ためらい","koName":"추입 주저","koCat1":"적 스킬","jpCat1":"赤スキル","koCat2":"공통","jpCat2":"共通","point":217},
{"id":425,"jpName":"トリック（前）","koName":"트릭 (앞)","koCat1":"적 스킬","jpCat1":"赤スキル","koCat2":"공통","jpCat2":"共通","point":217},
{"id":426,"jpName":"トリック（後）","koName":"트릭 (뒤)","koCat1":"적 스킬","jpCat1":"赤スキル","koCat2":"공통","jpCat2":"共通","point":217},
{"id":427,"jpName":"逃げ駆け引き","koName":"도주 심리전","koCat1":"적 스킬","jpCat1":"赤スキル","koCat2":"공통","jpCat2":"共通","point":174},
{"id":428,"jpName":"先行駆け引き","koName":"선행 심리전","koCat1":"적 스킬","jpCat1":"赤スキル","koCat2":"공통","jpCat2":"共通","point":174},
{"id":429,"jpName":"差し駆け引き","koName":"선입 심리전","koCat1":"적 스킬","jpCat1":"赤スキル","koCat2":"공통","jpCat2":"共通","point":174},
{"id":430,"jpName":"追込駆け引き","koName":"추행 심리전","koCat1":"적 스킬","jpCat1":"赤スキル","koCat2":"공통","jpCat2":"共通","point":174},
{"id":431,"jpName":"抜け駆け禁止","koName":"앞지르기 금지","koCat1":"적 스킬","jpCat1":"赤スキル","koCat2":"단거리","jpCat2":"短距離","point":262},
{"id":432,"jpName":"後方釘付","koName":"후방 못박기","koCat1":"적 스킬","jpCat1":"赤スキル","koCat2":"단거리","jpCat2":"短距離","point":262},
{"id":433,"jpName":"スピードイーター","koName":"스피드 이터","koCat1":"적 스킬","jpCat1":"赤スキル","koCat2":"마일","jpCat2":"マイル","point":217},
{"id":434,"jpName":"布石","koName":"포석","koCat1":"적 스킬","jpCat1":"赤スキル","koCat2":"마일","jpCat2":"マイル","point":217},
{"id":435,"jpName":"束縛","koName":"속박","koCat1":"적 스킬","jpCat1":"赤スキル","koCat2":"중거리","jpCat2":"中距離","point":217},
{"id":436,"jpName":"ささやき","koName":"속삭임","koCat1":"적 스킬","jpCat1":"赤スキル","koCat2":"중거리","jpCat2":"中距離","point":217},
{"id":437,"jpName":"スタミナイーター","koName":"스태미나 이터","koCat1":"적 스킬","jpCat1":"赤スキル","koCat2":"장거리","jpCat2":"長距離","point":217},
{"id":438,"jpName":"目くらまし","koName":"눈속임","koCat1":"적 스킬","jpCat1":"赤スキル","koCat2":"장거리","jpCat2":"長距離","point":129},
{"id":439,"jpName":"かく乱","koName":"교란","koCat1":"적 스킬","jpCat1":"赤スキル","koCat2":"선행","jpCat2":"先行","point":85},
{"id":440,"jpName":"リスタート","koName":"리스타트","koCat1":"적 스킬","jpCat1":"赤スキル","koCat2":"도주","jpCat2":"逃げ","point":217},
{"id":441,"jpName":"鋭い眼光","koName":"날카로운 눈빛","koCat1":"적 스킬","jpCat1":"赤スキル","koCat2":"선입","jpCat2":"差し","point":217},
{"id":442,"jpName":"まなざし","koName":"시선","koCat1":"적 스킬","jpCat1":"赤スキル","koCat2":"추입","jpCat2":"追込","point":217},
{"id":443,"jpName":"右回り×","koName":"시계(우)방향×","koCat1":"보라 스킬","jpCat1":"紫スキル","koCat2":"공통","jpCat2":"共通","point":-129},
{"id":444,"jpName":"左回り×","koName":"반시계(좌) 방향×","koCat1":"보라 스킬","jpCat1":"紫スキル","koCat2":"공통","jpCat2":"共通","point":-129},
{"id":445,"jpName":"東京レース場×","koName":"도쿄 경기장×","koCat1":"보라 스킬","jpCat1":"紫スキル","koCat2":"공통","jpCat2":"共通","point":-129},
{"id":446,"jpName":"中山レース場×","koName":"나카야마 경기장×","koCat1":"보라 스킬","jpCat1":"紫スキル","koCat2":"공통","jpCat2":"共通","point":-129},
{"id":447,"jpName":"阪神レース場×","koName":"한신 경기장×","koCat1":"보라 스킬","jpCat1":"紫スキル","koCat2":"공통","jpCat2":"共通","point":-129},
{"id":448,"jpName":"京都レース場×","koName":"교토 경기장×","koCat1":"보라 스킬","jpCat1":"紫スキル","koCat2":"공통","jpCat2":"共通","point":-129},
{"id":449,"jpName":"中京レース場×","koName":"나카교 경기장×","koCat1":"보라 스킬","jpCat1":"紫スキル","koCat2":"공통","jpCat2":"共通","point":-129},
{"id":450,"jpName":"札幌レース場×","koName":"삿포로 경기장×","koCat1":"보라 스킬","jpCat1":"紫スキル","koCat2":"공통","jpCat2":"共通","point":-129},
{"id":451,"jpName":"函館レース場×","koName":"하코다테 경기장×","koCat1":"보라 스킬","jpCat1":"紫スキル","koCat2":"공통","jpCat2":"共通","point":-129},
{"id":452,"jpName":"福島レース場×","koName":"후쿠시마 경기장×","koCat1":"보라 스킬","jpCat1":"紫スキル","koCat2":"공통","jpCat2":"共通","point":-129},
{"id":453,"jpName":"新潟レース場×","koName":"니가타 경기장×","koCat1":"보라 스킬","jpCat1":"紫スキル","koCat2":"공통","jpCat2":"共通","point":-129},
{"id":454,"jpName":"大井レース場×","koName":"오이 경기장×","koCat1":"보라 스킬","jpCat1":"紫スキル","koCat2":"공통","jpCat2":"共通","point":-129},
{"id":455,"jpName":"小倉レース場×","koName":"코쿠라 경기장×","koCat1":"보라 스킬","jpCat1":"紫スキル","koCat2":"공통","jpCat2":"共通","point":-129},
{"id":456,"jpName":"根幹距離×","koName":"근간거리×","koCat1":"보라 스킬","jpCat1":"紫スキル","koCat2":"공통","jpCat2":"共通","point":-129},
{"id":457,"jpName":"非根幹距離×","koName":"비근간거리×","koCat1":"보라 스킬","jpCat1":"紫スキル","koCat2":"공통","jpCat2":"共通","point":-129},
{"id":458,"jpName":"良バ場×","koName":"양호한 경기장×","koCat1":"보라 스킬","jpCat1":"紫スキル","koCat2":"공통","jpCat2":"共通","point":-129},
{"id":459,"jpName":"道悪×","koName":"진창길×","koCat1":"보라 스킬","jpCat1":"紫スキル","koCat2":"공통","jpCat2":"共通","point":-129},
{"id":460,"jpName":"春ウマ娘×","koName":"봄 우마무스메×","koCat1":"보라 스킬","jpCat1":"紫スキル","koCat2":"공통","jpCat2":"共通","point":-129},
{"id":461,"jpName":"夏ウマ娘×","koName":"여름 우마무스메×","koCat1":"보라 스킬","jpCat1":"紫スキル","koCat2":"공통","jpCat2":"共通","point":-129},
{"id":462,"jpName":"秋ウマ娘×","koName":"가을 우마무스메×","koCat1":"보라 스킬","jpCat1":"紫スキル","koCat2":"공통","jpCat2":"共通","point":-129},
{"id":463,"jpName":"冬ウマ娘×","koName":"겨울 우마무스메×","koCat1":"보라 스킬","jpCat1":"紫スキル","koCat2":"공통","jpCat2":"共通","point":-129},
{"id":464,"jpName":"雨の日×","koName":"비오는 날×","koCat1":"보라 스킬","jpCat1":"紫スキル","koCat2":"공통","jpCat2":"共通","point":-129},
{"id":465,"jpName":"内枠苦手","koName":"안쪽 그룹 서투름","koCat1":"보라 스킬","jpCat1":"紫スキル","koCat2":"공통","jpCat2":"共通","point":-129},
{"id":466,"jpName":"外枠苦手","koName":"바깥쪽 그룹 서투름","koCat1":"보라 스킬","jpCat1":"紫スキル","koCat2":"공통","jpCat2":"共通","point":-129},
{"id":467,"jpName":"GⅠ苦手","koName":"GⅠ질색","koCat1":"보라 스킬","jpCat1":"紫スキル","koCat2":"공통","jpCat2":"共通","point":-129},
{"id":468,"jpName":"小心者","koName":"소심한 성격","koCat1":"보라 스킬","jpCat1":"紫スキル","koCat2":"공통","jpCat2":"共通","point":-129},
{"id":469,"jpName":"ゲート難","koName":"게이트 난동","koCat1":"보라 스킬","jpCat1":"紫スキル","koCat2":"공통","jpCat2":"共通","point":-174},
{"id":470,"jpName":"引っ込み思案","koName":"내향적인 성격","koCat1":"보라 스킬","jpCat1":"紫スキル","koCat2":"공통","jpCat2":"共通","point":-129},
{"id":471,"jpName":"空回り","koName":"공회전","koCat1":"보라 스킬","jpCat1":"紫スキル","koCat2":"공통","jpCat2":"共通","point":-262},
{"id":472,"jpName":"あきらめ癖","koName":"포기하는 버릇","koCat1":"보라 스킬","jpCat1":"紫スキル","koCat2":"공통","jpCat2":"共通","point":-262},
{"id":473,"jpName":"コーナー回復×","koName":"코너회복×","koCat1":"보라 스킬","jpCat1":"紫スキル","koCat2":"공통","jpCat2":"共通","point":-262}]